### PR TITLE
Add node-local locks support in response bank

### PR DESCRIPTION
**Pull request by drinkbeer**
# Description

This PR aims to support node-local ephemral cache based locks in response bank.

### CODE REVIEW

**Comment by casperisfine** [comment]
Could you expand on what it's for, the advantages, etc?

**Comment by grcooper** [comment]
I don't think we need this in the response bank repo. Let's instead look at how we can solve this within our own repo, also as casper mentioned, let's remove the links to our private issues/prs.

**Comment by drinkbeer** [comment]
> Could you expand on what it's for, the advantages, etc?

We are migrating the lock keys from remote cache to node-local ephemeral cache. We have a beta flag to enable/disable the feature. The beta flag is passed to the response_bank through env variable. This PR want to support the node-local page cache locks.

**Comment by drinkbeer** [comment]
> Also you are linking from a public repo into two private issues.

Removed the links.

**Comment by casperisfine** [comment]
> We are migrating the lock keys from remote cache to node-local ephemeral cache. We have a beta flag to enable/disable the feature. The beta flag is passed to the response_bank through env variable.

I see. Well as @grcooper mentioned, this lock is purely a concern of the host app, so you can implement it however you want there, I really don't think you need any change upstream.

**Pull request closed without merging**
